apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kv-secrets
  namespace: default
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    keyvaultName: "${KEY_VAULT_NAME}"
    cloudName: ""
    objects: |
      array:
        - |
          objectName: JWTSECRET
          objectType: secret
    tenantId: "${TENANT_ID}"

  secretObjects:
  - secretName: app-secrets
    type: Opaque
    data:
    - objectName: JWTSECRET
      key: JWT_SECRET