apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-auth-api-egress
spec:
  podSelector:
    matchLabels:
      app: auth-api
  policyTypes:
    - Egress
  egress:
    - to:
        - podSelector:
            matchLabels:
              app: users-api
        - podSelector:
            matchLabels:
              app: zipkin
      ports:
        - protocol: TCP
          port: 8083
        - protocol: TCP
          port: 9411