apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-frontend-egress
spec:
  podSelector:
    matchLabels:
      app: frontend
  policyTypes:
    - Egress
  egress:
    - to:
        - podSelector:
            matchLabels:
              app: auth-api
        - podSelector:
            matchLabels:
              app: todos-api
        - podSelector:
            matchLabels:
              app: zipkin
      ports:
        - protocol: TCP
          port: 8000
        - protocol: TCP
          port: 8082
        - protocol: TCP
          port: 9411