apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-message-processor
  labels:
    app: log-message-processor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-message-processor
  template:
    metadata:
      labels:
        app: log-message-processor
    spec:
      containers:
        - name: log-message-processor
          image: log-message-processor:latest
          imagePullPolicy: Always
          env:
            - name: REDIS_HOST
              value: redis
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_CHANNEL
              value: log_channel
            - name: ZIPKIN_URL
              value: http://zipkin:9411/api/v2/spans