apiVersion: apps/v1
kind: Deployment
metadata:
  name: todos-api
  labels:
    app: todos-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todos-api
  template:
    metadata:
      labels:
        app: todos-api
    spec:
      containers:
      - name: todos-api
        image: todos-api:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8082
        env:
          - name: TODO_API_PORT
            value: "8082"
          - name: JWT_SECRET
            valueFrom:
              secretKeyRef:
                name: app-secrets
                key: JWT_SECRET
          - name: REDIS_HOST
            value: redis
          - name: REDIS_PORT
            value: "6379"
          - name: REDIS_CHANNEL
            value: log_channel
          - name: ZIPKIN_URL
            value: http://zipkin:9411/api/v2/spans
        volumeMounts:
            - name: secrets-store-inline
              mountPath: "/mnt/secrets-store"
              readOnly: true
        resources:
          requests:
            cpu: "100m"
          limits:
            cpu: "500m"
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.azure.com
            readOnly: true
            volumeAttributes:
              secretProviderClass: azure-kv-secrets