name: Validate Terraform on Pull Request

on:
  pull_request:
    branches: [ main ]
  
  workflow_dispatch:

jobs:
  terraform_validate_plan:
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      TF_VAR_location:           ${{ secrets.TF_LOCATION }}
      TF_VAR_resource_group_name: ${{ secrets.TF_RG_NAME }}
      TF_VAR_aks_cluster_name:   ${{ secrets.TF_AKS_CLUSTER_NAME }}
      TF_VAR_acr_name:           ${{ secrets.TF_ACR_NAME }}
      TF_VAR_key_vault_name:     ${{ secrets.TF_KEYVAULT_NAME }}
      TF_VAR_jwt_secret:         ${{ secrets.TF_JWT_SECRET }}
    defaults:
      run:
        working-directory: terraform/

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "3.1.2"
          terraform_wrapper: false

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -no-color -input=false